import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./contexts/AuthContext";
import { UserProvider } from "./contexts/UserContext";
import { UserFriendshipProvider } from "./contexts/FriendContext";
import { ProfileProvider } from './contexts/ProfileContext';
import background from "./images/background.jpg"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="background-wrapper">
          <img className="background" src={background.src} alt="background" />
          <div className="background-overlay"></div>
        </div>
        <AuthContextProvider>
          <UserProvider>
            <UserFriendshipProvider>
              <ProfileProvider>
                {children}
              </ProfileProvider>
            </UserFriendshipProvider>
          </UserProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
